import { useState, useEffect } from "react";
import { Loader, Card, FormField } from "../components";

const Home = () => {
  const [posts, setPosts] = useState<string[]>([]);
  const [loading, setLoading] = useState<boolean>(false);
  const [searchText, setSearchText] = useState<string>("");

  type Post = {
    _id: string;
    title: string;
  };
  type CardData = {
    data: Post[];
    title: string;
  };
  const RenderCards = ({ data, title }: CardData): JSX.Element => {
    if (data?.length > 0 && typeof data !== "string") {
      return (
        <>
          {data.map((post) => (
            <Card key={post._id} {...post} />
          ))}
        </>
      );
    }
    return <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">{title}</h2>;
  };

  return (
    <section className="max-w-7xl mx-auto">
      <div className="">
        <h1 className="font-extrabold text-[32px] text-app_black">The Community Showcase</h1>
        <p className="mt-2 text-app_gray text-[16px] max-w-[500px]">
          Browse through a collection of imaginative and visually stunning images generated by
          DALL-E AI
        </p>
      </div>
      <div className="mt-16">{/* <FormField /> */}</div>
      <div>
        {loading ? (
          <Loader />
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-app_gray text-3xl mb-3">
                Showing results for <span className="text-app_black">{searchText}</span>
              </h2>
            )}
            <div className="grid grid-cols-1 lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 gap-3">
              {searchText ? (
                <RenderCards data={[]} title="No search Results found" />
              ) : (
                <RenderCards data={[]} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
